version: '3.8'
services:
  db:
    image: postgres:13
    container_name: proxyBotDb
    restart: unless-stopped
    environment:
      POSTGRES_USER: proxybot
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: proxyBot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
